project:
  type: website
  render:
    - about.qmd
    - index.qmd
    - 00_openai.ipynb
    - 01_pyro_cov.ipynb
    - 01_wgs.qmd
    - 02_AFdesign.ipynb
    - 02_AlphaFold.ipynb
    - 02_binding_ddg.ipynb
    - 02_chroma.qmd
    - 02_RFdiffusion.ipynb

website:
  title: "Scientific Computation at large"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



