project:
  type: website
  render:
    - gatk.ipynb
    - pyro_cov.ipynb
    - AlphaFold.ipynb
    - binding_ddg.ipynb
    - chroma.qmd
    - RFdiffusion.ipynb

website:
  title: "Scientific Computation at large"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



