---
title: "Essays on Computational Biology"
format:
  html:
    code-fold: true
---

This website is a collection of tools I'm using for work in computational biology. Expected to be updated frequently.
Since I'm a trained Bayesian, the presentation of the tools and methods will inevitably has a Bayesian bias.

Click on the links on the left to navigate to the different sections.

# 01 Omics Analysis

Genomics, transcriptomics, proteomics, metabolomics, lipidomics, etc., uncovering the molecular mechanisms by studying their sequence information.

# 02 Computational protein design

Designing functional proteins, peptides, enzymes, antibodies, nanobodies, etc.

# 03 Computational micromolecule design

Designing small molecules that bind to protein targets, this includes inhibitors, activators, allosteric modulators, etc.

# 04 Molecular dynamics

Computer simulations to understand the molecular mechanisms of biological systems.

# 05 Machine learning

In depth analysis of key machine learning models and their applications.
